# Generated by Django 4.0.5 on 2023-01-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_collection_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='collection_description',
            new_name='description',
        ),
    ]
