# Generated by Django 4.0.5 on 2023-01-17 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_alter_collection_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='movie',
        ),
        migrations.CreateModel(
            name='CollectionMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.collection')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_movie', to='movie_app.movie')),
            ],
        ),
    ]
