# Generated by Django 4.0.5 on 2023-01-17 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_collection_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='movie',
        ),
        migrations.AddField(
            model_name='collection',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='movie_app.movie'),
        ),
    ]
