# Generated by Django 4.0.5 on 2023-01-17 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_remove_collection_movie_collection_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.movie'),
        ),
    ]
