# Generated by Django 4.0.5 on 2023-01-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0010_alter_collection_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='movie',
        ),
        migrations.AddField(
            model_name='collection',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='collections', to='movie_app.movie'),
        ),
    ]
