# Generated by Django 4.0.5 on 2023-01-17 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0011_remove_collection_movie_collection_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='movies',
        ),
        migrations.AddField(
            model_name='collection',
            name='movies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='movie_app.movie'),
        ),
    ]
