# Generated by Django 4.0.5 on 2023-01-19 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0015_genrerank_delete_collectionmovies'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='favourite_genres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='movie_app.genrerank'),
        ),
    ]
