# Generated by Django 4.0.5 on 2023-01-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0016_collection_favourite_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='favourite_genres',
        ),
    ]
