# Generated by Django 4.0.5 on 2023-01-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcount',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
