# Generated by Django 4.0.5 on 2023-01-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_counter', '0002_alter_requestcount_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcount',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
